name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *" # Executa a cada 12 horas
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Passo para gerar a animação de contribuições no GitHub
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: EricFaustino
          svg_out_path: dist/github-contribution-grid-snake.svg  # Verifique o diretório de saída

      # Passo para fazer o deploy no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # A branch de destino, verifique se existe
          build_dir: dist         # O diretório onde o SVG será gerado
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
