name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *" # Execute a cada 12 horas, no início da hora
  workflow_dispatch: # Permite a execução manual

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Passo para gerar a animação de contribuições no GitHub
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: EricFaustino
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Passo para fazer deploy no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # Certifique-se de que essa branch existe ou é criada
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
